# -*- coding: utf-8 -*-
"""Heatmap and Clsuter

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1utz7dVO8zhTero17-RauSDP-X7RDXKY1
"""

import pandas as pd
import seaborn as sns

from google.colab import files
x = files.upload()

data = pd.read_csv('heatmap.csv', index_col = 'Country')
data.head()

scaled_data = data.copy()

scaled_data = scaled_data.drop(['Language'], axis=1)

scaled_data

sns.clustermap(scaled_data,figsize=(5,5))